"""Run-local pressure ledger: time, light, noise, alarm, and fatigue.

Extracted from dungeon.py.  This module has no dependency on dungeon.py itself.
It reads and writes the ``pressure`` sub-dict that lives inside the dungeon
state dict, and emits clock ticks and tracking events on each advance.
"""
from __future__ import annotations

from hollowstar import clock
from hollowstar import tracking


def pressure(run, action_type, *, minutes=None, noise=0, rest=False):
    """Advance transparent run-local pressure; never secretly buffs opposition.

    Parameters
    ----------
    run:
        The active Run object.  The dungeon state is read from
        ``run.context['dungeon']``.
    action_type:
        The string action kind that triggered this advance (e.g.
        ``'investigate'``, ``'fight'``).
    minutes:
        Override the default time cost for ``action_type``.  If *None* the
        built-in cost table is used.
    noise:
        Additional noise units generated by this action.
    rest:
        If *True* fatigue is *reduced* rather than accumulated.

    Returns
    -------
    dict
        A pressure receipt with all post-advance counters.
    """
    d = run.context['dungeon']
    p = d.setdefault('pressure', {
        'minutes_elapsed': 0, 'fatigue': 0,
        'light_minutes': 120, 'noise': 0, 'alarm': 0, 'scale': 'mortal',
        'clocks': {'environment': 0, 'faction': 0}, 'history': [],
    })
    if minutes is None:
        minutes = {
            'observe_room': 1, 'inspect_room': 2, 'inspect_object': 2,
            'search_object': 10, 'open_object': 5, 'light_source': 1,
            'enter_subroom': 5, 'investigate': 5, 'negotiate': 3,
            'avoid': 5, 'fight': 1, 'attack': 1, 'cast': 1, 'move': 1,
            'rest': 360,
        }.get(action_type, 0)
    minutes = max(0, int(minutes))
    p['minutes_elapsed'] += minutes
    p['light_minutes'] = max(0, p.get('light_minutes', 120) - minutes)
    p['fatigue'] = max(0, p.get('fatigue', 0) + (minutes // 60 if not rest else -6))
    p['noise'] = max(0, p.get('noise', 0) + int(noise) - (1 if action_type in {'observe_room', 'rest'} else 0))
    if noise:
        p['alarm'] += max(0, int(noise))
    p['clocks']['environment'] += minutes
    if p['noise'] >= 10:
        p['clocks']['faction'] += 1
    d['greed'] = round(min(1.0, sum(int(item.get('value', 0)) for item in d.get('inventory', {}).values()) / 100), 4)
    d['attrition'] = round(min(1.0, (d.get('rooms_cleared', 0) / 20) + p['noise'] / 100 + p['alarm'] / 200), 4)
    fatigue = p['fatigue']
    p['scale'] = (
        'divine' if any(getattr(a, 'band', None) and getattr(a.band, 'name', '') == 'STEWARD' for a in run.party)
        else ('legendary' if d['floor'] >= 3 else 'mortal')
    )
    receipt = {
        'action': action_type, 'minutes': minutes,
        'time_after_minutes': p['minutes_elapsed'],
        'fatigue_after': fatigue, 'light_minutes_after': p['light_minutes'],
        'noise_after': p['noise'], 'alarm_after': p['alarm'],
        'greed': d['greed'], 'attrition': d['attrition'],
        'observable_escalation': p['noise'] >= 10 or p['fatigue'] >= 6,
        'scale': p['scale'],
    }
    p['history'].append(receipt)
    clock.emit(d, 'action', seconds=minutes * 60,
               room=f"{d['floor']}:{d['room']}", phase='gauntlet',
               payload={'action': action_type, 'minutes': minutes})
    tracking.ensure(d)['gameplay_minutes'] = p['minutes_elapsed']
    tracking.action(d)
    return receipt
