/* Primary client polish; built on the existing host command loop. */
const U=HSRUI;
const esc=U.escape;
const safeList = value => Array.isArray(value) ? value : [];
S.filter='';
S.armory=[]; S.armoryFilters={class:'',gender:'',race:''};
const validScreens=[...tabs.map(t=>t[0]),'title','residents'];
if(validScreens.includes(location.hash.slice(1))) S.screen=location.hash.slice(1);
tabs.splice(4,0,['residents','♧','Residents']);
// Preview examples are exported from the real Item/affix loader, never a UI rules engine.
fetch('web/item-preview.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(p=>{demo.party[0].equipment=p.equipment;if(!S.live)render()}).catch(()=>{});
fetch('web/visual-armory.json').then(r=>r.json()).then(p=>{S.armory=p.items||[];S.armorySelectors=p.selectors||{};if(!S.live)render()}).catch(()=>{});
function prefs(){try{return JSON.parse(localStorage.getItem('hsr-display')||'{}')}catch{return {}}}
const preferences=prefs();
document.body.classList.toggle('reduced',preferences.motion==='reduced');
document.body.classList.toggle('soft',preferences.effects==='soft');
if(['1','1.15','1.3'].includes(preferences.scale))document.documentElement.style.setProperty('--scale',preferences.scale);
function storePrefs(){try{localStorage.setItem('hsr-display',JSON.stringify({motion:document.body.classList.contains('reduced')?'reduced':'full',effects:document.body.classList.contains('soft')?'soft':'full',scale:document.documentElement.style.getPropertyValue('--scale')||'1'}))}catch{}}
equipment=function(){const a=actor(),gear=U.gear(a),inventory=S.view.inventory||[],s=S.armorySelectors||{},f=S.armoryFilters;const matches=x=>(!f.class||safeList(x.classes).includes(f.class))&&(!f.gender||safeList(x.tones).includes(f.gender))&&(!f.race||safeList(x.races).includes(f.race));const options=(key,label)=>`<label class="armory-filter"><span>${esc(label)}</span><select data-armory-filter="${esc(key)}"><option value="">All</option>${safeList(s[key+'s']).map(v=>`<option ${f[key]===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;const armory=S.armory.filter(matches);return `<div class="split"><section class="panel"><div class="eyebrow">Selected adventurer</div>${actors()}<div class="rule"></div><p class="muted">Select equipment to read its stats, material tells, and attached effects.</p></section><section class="panel"><h2>${esc(a.name)}</h2><p class="muted">Equipped gear & carried Runes</p><div class="item-toolbar"><input id="item-filter" aria-label="Filter equipment and inventory" placeholder="Find an item, prefix, or suffix…" value="${esc(S.filter)}"><span id="item-count" class="muted"></span></div><h3>Equipped gear</h3><div class="cards" style="margin-top:15px">${gear.map((g,i)=>U.card(g,'gear',i)).join('')||'<p class="muted">No public equipment listed.</p>'}</div><div class="rule"></div><h3>Visual armory</h3><p class="muted">Illustrative base forms. Class, race, and gender are presentation filters; stats remain host-returned.</p><div class="armory-filters">${options('class','Class')}${options('gender','Gender')}${options('race','Race')}</div><div class="armory-grid">${armory.map(x=>`<article class="armory-card"><div class="armory-silhouette" aria-hidden="true">${esc(x.silhouette)}</div><strong>${esc(x.name)}</strong><small>${esc(x.kind)} · ${esc(x.material)}</small><small>${safeList(x.classes).map(esc).join(' · ')}</small></article>`).join('')||'<p class="muted">No visual forms match these filters.</p>'}</div><div class="rule"></div><h3>Carried items</h3><div class="cards" style="margin-top:15px">${inventory.map((g,i)=>U.card(g,'item',i)).join('')||'<p class="muted">Your inventory is empty.</p>'}</div><div class="rule"></div><h3>Reliquary Imprints</h3>${U.slots(S.view,a.id)}<p class="muted">Armor class on the roster is the host’s final total. Equipment bonuses are not added again.</p></section></div>`};
function residents(){const npcs=Object.values(S.view.room?.npcs||{});return `<div class="content-grid"><section class="panel"><div class="eyebrow">People nearby</div><h2>Residents</h2>${npcs.length?npcs.map(n=>`<article class="npc-card"><span class="portrait">${esc((n.name||n.role||'?')[0])}</span><div><h3>${esc(n.name||n.role||'Resident')}</h3><p class="muted">${esc(n.role||'Role not reported')}</p>${n.disposition!=null?'<small>Disposition: '+esc(n.disposition)+'</small>':''}<button data-talk="${esc(n.id||n.npc_id||n.role)}">Talk</button></div></article>`).join(''):'<p class="muted" style="margin-top:22px">No residents are visible in this readout.</p>'}</section><section class="panel"><img class="npc-portrait" src="web/assets/townsperson.png" alt="Generic adult town craftswoman portrait"><h3 style="margin-top:15px">Townsfolk portrait study</h3><p class="muted">Generic role illustration. Named residents keep their own identity; portraits appear here as an art study until assigned.</p></section></div>`}
const originalOptions=options;
options=function(){return originalOptions()+`<section class="panel" style="max-width:680px;margin-top:18px"><h3>Local connection</h3><p class="muted">Check the shared engine or reference this interface from another client.</p><div class="actions"><button data-ping>Ping engine</button><a href="/api/ui">Interface manifest</a><a href="/web/index.html">Compact browser layout</a></div><details><summary>Current public view</summary><pre>${esc(JSON.stringify(S.view,null,2))}</pre></details></section>`};
const originalRender=render;
render=function(){originalRender();try{history.replaceState(null,'','#'+S.screen)}catch{}};
const originalBind=bind;
bind=function(){originalBind();document.querySelectorAll('[data-gear]').forEach(b=>b.onclick=()=>modal(U.name(U.gear(actor())[Number(b.dataset.gear)]),U.detail(U.gear(actor())[Number(b.dataset.gear)])));document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{const item=S.view.inventory[Number(b.dataset.item)];modal(U.name(item),U.detail(item)+(S.live&&item.kind==='imprint'&&item.identified?'<button id="equip-item">Equip on '+esc(actor().name)+'</button>':'')+(S.live&&item.kind==='imprint'&&!item.identified&&S.view.available_actions?.some(a=>a.id==='identify')?'<button id="identify-item">Identify through the host</button>':''));$('#equip-item')?.addEventListener('click',()=>{const intent='equip '+actor().id+' '+item.id;$('#modal').close();work(async()=>accept(await host('design_turn',{run_id:S.runId,intent,public_only:true}))) });$('#identify-item')?.addEventListener('click',()=>{$('#modal').close();work(async()=>{accept(await host('design_turn',{run_id:S.runId,intent:'identify '+item.id,public_only:true}));})})});
document.querySelectorAll('[data-armory-filter]').forEach(el=>el.onchange=e=>{S.armoryFilters[e.target.dataset.armoryFilter]=e.target.value;render()});
const filter=$('#item-filter');function applyFilter(){let count=0;document.querySelectorAll('.item-card').forEach(card=>{const shown=card.textContent.toLowerCase().includes(S.filter.toLowerCase());card.hidden=!shown;if(shown)count++});if($('#item-count'))$('#item-count').textContent=count+' items'}if(filter){filter.oninput=e=>{S.filter=e.target.value;applyFilter()};applyFilter()}
document.querySelectorAll('[data-talk]').forEach(b=>b.onclick=()=>{if(!S.live){modal('Conversation preview','<p>Connect a run to speak with a visible resident.</p>');return}work(async()=>{accept(await host('design_turn',{run_id:S.runId,intent:'talk to '+b.dataset.talk,public_only:true}));})});
$('[data-ping]')?.addEventListener('click',()=>work(async()=>{const start=performance.now();await host('health');S.note='Engine answered in '+Math.round(performance.now()-start)+' ms.'}));
for(const id of ['motion','text-size','effects'])$('#'+id)?.addEventListener('change',storePrefs);
document.querySelectorAll('img').forEach(img=>img.onerror=()=>{const replacement=document.createElement('span');replacement.className='item-art art-fallback';replacement.textContent='Art unavailable';img.replaceWith(replacement)});
};
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(validScreens.includes(next)){S.screen=next;render()}});
// Read-only public client reference for agents and embedded consumers.
window.HollowStarUI=Object.freeze({schema:'hsr-ui-client-1',getPublicView:()=>structuredClone(S.view),getStatus:()=>({screen:S.screen,run_id:S.runId,connected:S.live,busy:S.busy}),navigate:screen=>{if(!validScreens.includes(screen))throw Error('Unknown screen');S.screen=screen;render()}});
render();
